### ISSUE TITLE
Life Steal not working properly.

### ISSUE THREAD

**Issue by Noiseyguest** [SirHenryVII/LifeStealPlugin#10]
So, whenever a player loses/gains a heart, and rejoins the server that player's hearts gets reset back to 10. Here's the config file:
`DefaultHealth: 16.0
HealthLostOnDeath: 2.0
HealthGainedOnKill: 2.0
LoseLifeIfNotKilledByPlayer: false
HeartRecipe:
  Slot0: DIAMOND_BLOCK
  Slot1: OBSIDIAN
  Slot2: DIAMOND_BLOCK
  Slot3: GOLD_BLOCK
  Slot4: NETHERITE_INGOT
  Slot5: GOLD_BLOCK
  Slot6: DIAMOND_BLOCK
  Slot7: OBSIDIAN
  Slot8: DIAMOND_BLOCK`

**Comment by SirHenryVII** [comment]
I apologize for not responding sooner. Due to the fact that no other player seems to have this error, I am going to have to guess that it has something to do with some other plugin you have installed that messes with player health.
