### ISSUE TITLE
Feature Request Add Reset and Reload Command And Another Issue

### ISSUE THREAD

**Issue by priyam1234-spec** [SirHenryVII/LifeStealPlugin#11]
It Resets Everyones Hearts.
The Issue Is I edit the config but the changes doesnt reflect into the game

**Comment by SirHenryVII** [comment]
I apologize for not responding sooner. The current stable version of this plugin does not have the SMP reset command, as I am currently working to implement it. If you are having issues with the config, please try restarting the server after you make an edit.
