### ISSUE TITLE
Feature - Add Permission for the Withdraw cmd

### ISSUE THREAD

**Issue by AabegR** [SirHenryVII/LifeStealPlugin#7]
Hello there!
Would it be possible to add a permission node to the withdraw cmd? So only specific players with that cmd can run the withdraw cmd,
Some permission called for example: ls.withdraw
:)

**Comment by SirHenryVII** [comment]
I apologize for not responding sooner, but yes I am currently working on that feature.

**Comment by AabegR** [comment]
Bro it's been a year... I forgot lifestyles even existed lmao. But thank you Sir Henry the 7th for your dedication. Hopefully I get to use your plugin again soon :)

**Comment by SirHenryVII** [comment]
Took a break from spigot to focus on school but I'm excited to get back into it! Thank you for using my plugin.
