### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by B3N555** [SirHenryVII/LifeStealPlugin#8]
Hi I rlly like the plug-in but is their anyway I can stop the withdraw plug-in I don’t want anyone on my server using it

**Comment by SirHenryVII** [comment]
I am working on an update at the moment that will add a permission for the withdraw command, however for the time being here is what you can do: If you know how to compile the plugin yourself you can download the code from this repository and remove line 27 of LifeSteal.java and lines 8-10 of plugin.yml. Once you compile the withdraw command will no longer exist.
